Add multientities batch to aerospike template
aerospike-community/spring-data-aerospike pull request #162
Opened 2021-03-11 13:38 UTC by mrozk

2021-03-11 14:26 UTC, reugn requested changes

2021-03-11 14:26 UTC, reugn commented on src/main/java/org/springframework/data/aerospike/core/AerospikeTemplate.java
> +		Assert.notNull(entitiesKeys, "Map of entities ids must not be null!");
@mrozk why not
```java
return entitiesKeys.entrySet().stream().collect(Collectors.toMap(Map.Entry::getKey,
				e -> findByIdsInternal(e.getValue(), e.getKey())));
```
which makes this method redundant.

2021-03-11 15:04 UTC, mrozk commented on src/main/java/org/springframework/data/aerospike/core/AerospikeTemplate.java
> +		Assert.notNull(entitiesKeys, "Map of entities ids must not be null!");
In your scenario you will make N batch requests, this method does 1 batch request

2021-03-15 14:16 UTC, Aloren commented on src/main/java/org/springframework/data/aerospike/core/AerospikeOperations.java
> +	Map<Class<?>, Collection<?>> findEntitiesByIds(Map<Class<?>, Collection<?>> keysMap);
please rename to `findByIds`.
Also it would be nice to have javadoc about tis method

2021-03-15 14:18 UTC, Aloren commented on src/main/java/org/springframework/data/aerospike/core/AerospikeTemplate.java
> +	private <T> List<Key> toKeysList(Class<T> entityClass, Iterable<?> ids) {
`ids` has list type in the public method. what is the reason for it to be iterable here?

2021-03-15 14:18 UTC, Aloren commented on src/main/java/org/springframework/data/aerospike/core/AerospikeTemplate.java
> +		Assert.notNull(entityClass, "List of ids must not be null!");
message is invalid. please fix

2021-03-15 14:24 UTC, Aloren commented on src/main/java/org/springframework/data/aerospike/core/AerospikeTemplate.java
> +		Record[] records = client.get(null, keys);
if request is empty, i think, we can skip requesting anything from the client?

2021-03-15 14:25 UTC, Aloren commented on src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateFindByEntitiesTests.java
> +    public void shouldReturnMapWithEmptyResultsOnEmptyRequest() {
what's the difference from `shouldReturnMapWithEmptyResults` ?

2021-03-15 14:27 UTC, Aloren commented on src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateFindByEntitiesTests.java
> +
pls add tests for requesting bunch of keys where some of them are missing, all of them are missing. probably some other corner cases as well

2021-03-15 14:29 UTC, reugn commented on src/main/java/org/springframework/data/aerospike/core/AerospikeOperations.java
> +	Map<Class<?>, Collection<?>> findEntitiesByIds(Map<Class<?>, Collection<?>> keysMap);
@Aloren I find this method's signature vague.

2021-03-15 14:33 UTC, reugn commented on src/main/java/org/springframework/data/aerospike/core/AerospikeTemplate.java
> +		Assert.notNull(entitiesKeys, "Map of entities ids must not be null!");
Have you benchmarked both?

2021-03-15 16:03 UTC, mrozk commented on src/main/java/org/springframework/data/aerospike/core/AerospikeTemplate.java
> +		Assert.notNull(entitiesKeys, "Map of entities ids must not be null!");
I suppose that batches for different set work the same as batches to single set. Also if we cover every request in spring retry we will receive profit from requests count perspective. We have use cases where  we don't want to send 2 request because it is too expensive - timeout 50ms + 3 retries on each (if aerospike is glitching)

2021-03-15 16:27 UTC, mrozk commented on src/main/java/org/springframework/data/aerospike/core/AerospikeTemplate.java
> +	private <T> List<Key> toKeysList(Class<T> entityClass, Iterable<?> ids) {
Fixed to Collection

2021-03-15 16:27 UTC, mrozk commented on src/main/java/org/springframework/data/aerospike/core/AerospikeTemplate.java
> +		Assert.notNull(entityClass, "List of ids must not be null!");
done

2021-03-15 16:50 UTC, mrozk commented on src/main/java/org/springframework/data/aerospike/core/AerospikeTemplate.java
> +		Record[] records = client.get(null, keys);
Added check on the beginning of the method

2021-03-15 16:59 UTC, mrozk commented on src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateFindByEntitiesTests.java
> +    public void shouldReturnMapWithEmptyResultsOnEmptyRequest() {
I have renamed methods to clarify their functionality

2021-03-15 16:59 UTC, mrozk commented on src/test/java/org/springframework/data/aerospike/core/AerospikeTemplateFindByEntitiesTests.java
> +
done

2021-03-17 13:01 UTC, reugn reviewed
This method has a number of code smells:
* Use of wildcards in return types.
* The type of the parameter is the same as the return type and wildcards make it ambiguous.
* The method's name doesn't add clarification.

The API user will not easily understand what this method does.
I would suggest returning something like:
```java
@FunctionalInterface
interface GroupedEntities {
    <T> List<T> getByClass(Class<T> entityClass);
}
```

2021-03-26 07:28 UTC, Aloren commented
@mrozk did you have a chance to update your PR with the changes requested by @reugn ? this will definitely improve the method readability significantly

2021-03-26 07:38 UTC, mrozk commented
> @mrozk did you have a chance to update your PR with the changes requested by @reugn ? this will definitely improve the method readability significantly

@Aloren I'm going to update the PR today or tomorrow with suggested changes

2021-03-30 10:30 UTC, reugn requested changes
@mrozk LGTM.
Please add this functionality to `ReactiveAerospikeOperations`.

2021-03-30 10:30 UTC, reugn commented on src/main/java/org/springframework/data/aerospike/core/AerospikeTemplate.java
> +	 * to get result as spring data arospike entities grouped by entity type.
typo

2021-03-30 10:30 UTC, reugn commented on src/main/java/org/springframework/data/aerospike/core/model/GroupedKeys.java
> +package org.springframework.data.aerospike.core.model;
Please add a copyright header.

2021-03-30 10:30 UTC, reugn commented on src/main/java/org/springframework/data/aerospike/core/model/GroupedEntities.java
> +package org.springframework.data.aerospike.core.model;
Please add a copyright header.

2021-04-11 16:17 UTC, reugn commented
@mrozk what are your plans regarding this PR?

2021-04-14 14:17 UTC, mrozk commented on src/main/java/org/springframework/data/aerospike/core/model/GroupedEntities.java
> +package org.springframework.data.aerospike.core.model;
done

2021-04-14 14:17 UTC, mrozk commented on src/main/java/org/springframework/data/aerospike/core/AerospikeTemplate.java
> +	 * to get result as spring data arospike entities grouped by entity type.
done

2021-04-14 14:20 UTC, mrozk commented
> @mrozk what are your plans regarding this PR?

@reugn I'm going to finish reactive implementation this week. We can either wait for it and release both implementation or release sync version first and release async separately.

2021-04-25 08:23 UTC, roimenashe commented
@mrozk any updates regarding the async functionality?

2021-04-30 12:23 UTC, mrozk commented
> @mrozk any updates regarding the async functionality?

Hi! done

2021-05-02 08:28 UTC, reugn commented
Thank you @mrozk .

2021-05-02 08:29 UTC, reugn approved these changes

2021-05-18 11:23 UTC, merged